monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.usb-FIIO_FiiO_K11-01.pro-output-0"
      }
    ]
    actions = {
      update-props = {
        audio.allowed-rates = [ 44100 48000 88200 96000 176400 192000 352800 384000 ]
        audio.allowed-formats = [ "S24_32LE" "S32LE" "S16LE" ]
        
        api.alsa.period-size = 1024
        api.alsa.period-num  = 2
        api.alsa.headroom    = 0
        node.suspend-on-idle = false
      }
    }
  }
]
