#!/bin/bash

# Author : https://github.com/Crash-Zeus

readonly command=$1

# Set the source audio player here.
# Examples: spotify, vlc, chrome, mpv and others.
# See more here: https://github.com/altdesktop/playerctl/#selecting-players-to-control
readonly PLAYER="spotifyd"

readonly FORMAT_MSG="{{ xesam:title }} - {{ xesam:artist }}"
readonly FORMAT_DURATION="{{ duration(mpris:length) }} minutes"
readonly FORMAT_ICON="{{ mpris:artUrl }}"

function get_metadata() {
    MSG=$(playerctl --player=$PLAYER metadata --format "$FORMAT_MSG")
    DURATION=$(playerctl --player=$PLAYER metadata --format "$FORMAT_DURATION")
    ICON_URI=$(playerctl --player=$PLAYER metadata --format "$FORMAT_ICON")
}

function notify() {
    curl -s -o /tmp/spotify-icon.png $ICON_URI
    dunstify --appname="spotify" "$MSG" "<i>$DURATION</i>" -i /tmp/spotify-icon.png
}

case $command in
    
    "--notify")
        get_metadata
        notify
    ;;
    
    *)
        echo "No command specified."
        echo ""
        echo "Available commands :"
        echo "--notify         Notify event using dunstify"
        exit 0
    ;;
esac
