--force-dark-mode
--ozone-platform-hint=auto
--force-color-profile=srgb
--disable-features=WaylandWpColorManagerV1,UseHDRTransferFunctions
--enable-features=Vulkan,VulkanFromANGLE,DefaultANGLEVulkan,AcceleratedVideoDecodeLinuxZeroCopy,AcceleratedVideoEncoder
