--force-dark-mode
--ozone-platform-hint=wayland
--force-color-profile=srgb
--disable-features=Vulkan,WaylandWpColorManagerV1,UseHDRTransferFunctions
--enable-features=AcceleratedVideoDecodeLinuxZeroCopy,AcceleratedVideoEncoder
