#!/bin/bash

if [ -z "$1" ]; then
    echo "No wallpaper file specified"
    exit 1
fi

WALLPAPER="$(realpath -s "$1")"

if [ ! -f "${WALLPAPER}" ]; then
    echo "Wallpaper file does not exist: ${WALLPAPER}"
    exit 1
fi

ln -sf "${WALLPAPER}" ~/.config/hypr/wallpaper.png

killall hyprpaper 2>/dev/null
hyprctl dispatch 'hl.dsp.exec_cmd("hyprpaper")'
