#!/bin/bash

readonly cmd="$1"
readonly max=6

current=$(hyprctl activeworkspace -j | jq '.id')

if [ "$cmd" = "next" ]; then
    next=$(( (current % max) + 1 ))
elif [ "$cmd" = "prev" ]; then
    next=$(( (current + max - 2) % max + 1 ))
fi

hyprctl dispatch workspace "$next"
