#! /bin/sh

LAPTOP=false
if [ ! -z "$(upower -d | grep BAT)" ]
then
    LAPTOP=true
fi

export NOTIFICATION_SOUND="$HOME/.config/dunst/notif.mp3"
export LAPTOP=$LAPTOP

xsetroot -cursor_name left_ptr
setxkbmap fr
sxhkd &
xhost +local:root

MAIN_MONITOR=$(xrandr | grep primary | awk '{print $1}')
SECOND_MONITOR=$(xrandr | grep connected | awk '{i++}i==2'| awk '{print $1}')

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc &
pgrep -x picom > /dev/null || picom -b --config ~/.config/picom/picom.conf &

bspc monitor ${MAIN_MONITOR} -d 1 2 3 4 5 6

bspc config border_width         3
bspc config focused_border_color "#471d59"
bspc config window_gap           12
bspc config split_ratio          0.6
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle       true

# Consider disabled / unplugged monitors as unavailable
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -a yad-calendar state=floating

# Focus any click
bspc config click_to_focus any

# Make cursor smooth
# 1000/[refresh rate] to get value
bspc config pointer_motion_interval 10

# Autostart applications
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
pgrep -x dunst > /dev/null || dunst -config ~/.config/dunst/dunstrc &
feh --bg-fill --no-screen-clip --no-xinerama ~/.config/wallpaper
pgrep -x playerctld > /dev/null || playerctld daemon &
bash ~/.config/polybar/launch.sh &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x emote > /dev/null || emote &

# Autostart bluetooth
if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]
then
    bluetoothctl power on
fi

# notify good start
dunstify --appname="bspwmrc" --urgency="LOW" "BSPWM loaded at $(date +'%T')"
