#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc &
pgrep -x picom > /dev/null || picom -b --experimental-backends --config ~/.config/picom/picom.conf &

# Autostart applications

bash ~/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dunst -config ~/.config/dunst/dunstrc &
feh --bg-fill --no-screen-clip --no-xinerama ~/.config/wallpaper
playerctld daemon &
flameshot &
slimbookbattery --minimize &

# Bspwm config

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         3
bspc config focused_border_color "#471d59"
bspc config window_gap           12
bspc config split_ratio          0.6
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle       true

# Consider disabled / unplugged monitors as unavailable
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Make teams open on second screen always
bspc rule -a teams-for-linux desktop=6
bspc rule -a yad-calendar state=floating

# Focus any click
bspc config click_to_focus any
# Make cursor smooth
# 1000/[refresh rate] to get value
bspc config pointer_motion_interval 40

# Autostart bluetooth
if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]
then
    bluetoothctl power on
fi

# notify good start
dunstify --appname="bspwmrc" --urgency="LOW" "loaded at $(date +'%T')" -i /usr/share/icons/Tela-circle-black-dark/scalable/apps/cs-display.svg
