# Wayle configuration entrypoint

imports = [
    "config.d/base/general.toml",
    "config.d/base/styling.toml",
    "config.d/base/bar.toml",
    "config.d/modules/dashboard.toml",
    "config.d/modules/hyprland-workspaces.toml",
    "config.d/modules/cpu.toml",
    "config.d/modules/ram.toml",
    "config.d/modules/storage.toml",
    "config.d/modules/media.toml",
    "config.d/modules/cava.toml",
    "config.d/modules/window-title.toml",
    "config.d/modules/clock.toml",
    "config.d/modules/network.toml",
    "config.d/modules/volume.toml",
    "config.d/modules/microphone.toml",
    "config.d/modules/bluetooth.toml",
    "config.d/modules/systray.toml",
    "config.d/modules/notification.toml",
    "config.d/modules/battery.toml",
    "config.d/modules/weather.toml",
    "config.d/custom/updates.toml",
]
