[modules.media]
format = "{{ title }} by {{ artist }}"
icon-show = true
icon-color = "accent"
icon-bg-color = "bg-elevated"
label-show = true
label-color = "fg-default"
label-max-length = 35
button-bg-color = "bg-elevated"
border-show = false
left-click = "dropdown:media"
players-ignored = ["*Ankama*", "*brave*"]
player-priority = ["*io.github.lullabyX.sone*", "*SONE*"]
player-icons = { 
    "io.github.lullabyX.sone" = "si-tidal-symbolic",
    "org.mpris.MediaPlayer2.io.github.lullabyX.sone" = "si-tidal-symbolic",
    "*SONE*" = "si-tidal-symbolic"
}
