[modules.microphone]
icon-show = true
icon-color = "accent"
icon-bg-color = "bg-elevated"
label-show = true
label-color = "fg-default"
button-bg-color = "bg-elevated"
border-show = false
left-click = "dropdown:audio"
right-click = "pavucontrol -t 4"
middle-click = "wayle audio input-mute"
