[modules.window-title]
format = "{{ title }}"
icon-name = "si-tidal-symbolic"
icon-mappings = {
    "*sone*" = "si-tidal-symbolic",
    "*io.github.lullabyX.sone*" = "si-tidal-symbolic",
    "title:*SONE*" = "si-tidal-symbolic"
}
icon-show = true
icon-color = "accent"
icon-bg-color = "bg-elevated"
label-show = true
label-color = "fg-default"
label-max-length = 50
button-bg-color = "bg-elevated"
border-show = false
