#!/bin/bash

HDR_CONFIG=", highrr, auto, 1, bitdepth, 10, cm, hdr, sdrbrightness, 1.3, sdrsaturation, 1"

SDR_CONFIG=", highrr, auto, 1"

hyprctl keyword monitor "$SDR_CONFIG"

sleep 0.5

grim -g "$(slurp -d)" - | magick - -colorspace sRGB -depth 8 -define png:color-type=2 -strip png:- | wl-copy

notify-send "Screenshot SDR" "Image copied to clipboard"

sleep 0.2
hyprctl keyword monitor "$HDR_CONFIG"
notify-send "Hyprland" "HDR reactivated"
