#!/bin/bash

HDR_CONFIG=", highrr, auto, 1, bitdepth, 10, cm, hdr, sdrbrightness, 1.3, sdrsaturation, 1"

SDR_CONFIG=", highrr, auto, 1"

hyprctl keyword monitor "$SDR_CONFIG"

sleep 0.5

TMP_SHOT=$(mktemp --suffix .png)
grim -g "$(slurp -d)" "$TMP_SHOT"

hyprctl keyword monitor "$HDR_CONFIG"
notify-send "Hyprland" "HDR réactivé"

satty -f "$TMP_SHOT" &

notify-send "Screenshot SDR" "Image copiée dans le presse-papier (édition possible)"

sleep 2
rm -f "$TMP_SHOT"
